Add missing config header values to build.zig
Two fields are missing a value, and every field must be set for this build step
to succeed.

```
$ zig build
install
└─ install pcre2-8
   └─ zig build-lib pcre2-8 Debug native
      └─ configure cmake header config-cmake.h.in to config.h failure
error: /home/jordan/dev/pcre2/config-cmake.h.in:52: unable to substitute variable: error: MissingValue
error: /home/jordan/dev/pcre2/config-cmake.h.in:53: unable to substitute variable: error: MissingValue
error: HeaderConfigFailed
```